#%RAML 1.0 Trait
headers:
  client_id: 
   default: "rtjdfygjk,lo8iu7y645ertrytujbmnv"
   maxLength: 100
   minLength: 1
  client_secret: 
    default: "rtjdfygjk,lo8iu7y645ertrytujbmnv"
    maxLength: 100
    minLength: 1
  